### ISSUE TITLE
Friendship invite filtering

### ISSUE THREAD

**Issue by Valian** [pleniec/pvpc-core#10]
To check if user has already invited me to friends or if I invited him I must get all friendship invites relative to both users.

**Comment by pleniec** [comment]
users#index and users#show renders additional field (relation_to_current_user) which holds information about relation of rendered model towards current user.
Values:
* SENT_FRIENDSHIP_INVITE - user sent invite to current user
* RECEIVED_FRIENDSHIP_INVITE - user received invite from current user
* FRIEND - user is a friend to current user
* STRANGER - users are not friends and they don't have any pending invites
