### ISSUE TITLE
Id of relation when querying for user

### ISSUE THREAD

**Issue by Valian** [pleniec/pvpc-core#11]
In #10 you added field that tells me hat kind of friendship relation certain user has, but also i need id of that relation, to accept / delete etc. Currently I must get full list and find matching one.

**Comment by Valian** [comment]
I'm prepared for structure 'relation_to_current_user': {'type': TYPE, 'id': ID}. if user is stranger for me, id should be none or not exist

**Comment by pleniec** [comment]
Just use friendships to remove user from friends and frienship_invites to accept.

**Comment by Valian** [comment]
@pleniec I know how to do this, but i don't have friendships or friendships_invites id. Read question again.

**Comment by pleniec** [comment]
1. Get list of friendships/friendship_invites
2. Find the one that matches friend's/from_user's user_id
3. ???

**Comment by Valian** [comment]
I won't use index endpoints for searching, it's dumb. User can have many pending invites, I would have to download all of them just to find one record. You are returning name of relation, return relation id and everything will be much easier.
