### ISSUE TITLE
TeamInvite team scope

### ISSUE THREAD

**Issue by Valian** [pleniec/pvpc-core#14]
As I see I can't filter TeamInvites by team_id. Also, who is able to accept Invite, only team leader? And what if invite was sent to user from team, is user able to accept it?

**Comment by Valian** [comment]
Also, why all fields are required to create Invite? When i want to apply to team, what should I put into to_user_id field?

**Comment by pleniec** [comment]
team_id scope is useless. Applying to team will be done using TeamMembershipRequest model.
