### ISSUE TITLE
GameOwnership endpoint doesn't set/return nickname field

### ISSUE THREAD

**Issue by Valian** [pleniec/pvpc-core#22]
Unable to set nickname in GameOwnership model. Both POST or PATCH are not working, always returns model without nickname field

**Comment by pleniec** [comment]
WITHOUT nickname field or WITH nickname field set to null?

**Comment by Valian** [comment]
without

**Comment by pleniec** [comment]
Cannot reproduce. Curled and everything worked as expected.
