### ISSUE TITLE
Problem with checking if two users are friends

### ISSUE THREAD

**Issue by Valian** [pleniec/pvpc-core#9]
Now only way to do so is to download all friends of given user and check if other is among them. I need it for user view, where I have to check if given person is my friend or not. Solution: create filter to_user to FriendshipsController. Same is needed in TeamsInviteController

**Comment by Valian** [comment]
Also, but it's no needed right now, I will need filtering friends by name.

**Comment by pleniec** [comment]
https://github.com/pleniec/pvpc-core/issues/10
